

CREATE PROC [dbo].[SP_CHECK_DANGNHAP]
@TENLOGIN NVARCHAR (50)
AS
BEGIN
	DECLARE @TENUSER NVARCHAR(50)
	SELECT @TENUSER=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)
	SELECT USERNAME = @TENUSER,
		HOTEN = (SELECT HO+ ' '+ TEN FROM GIANGVIEN WHERE MAGV = @TENUSER ),
		TENNHOM= NAME
			FROM sys.sysusers
				WHERE UID = (SELECT GROUPUID
					FROM SYS.SYSMEMBERS
						WHERE MEMBERUID= (SELECT UID FROM sys.sysusers
							WHERE NAME=@TENUSER))
END

CREATE PROC [dbo].[SP_CHECK_LOGIN_SV]
@TENLOGIN NVARCHAR (50), @MASV NCHAR(10), @PASS NVARCHAR(40)
AS
BEGIN
	IF EXISTS(SELECT * FROM SINHVIEN SV WHERE SV.MASV=@MASV AND SV.PASSWORD=@PASS)
	BEGIN
		DECLARE @TENUSER NVARCHAR(50)
		SELECT @TENUSER=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)

		SELECT MASV=@MASV, HOTEN=(SELECT HO+ ' '+ TEN FROM SINHVIEN WHERE MASV = @MASV ),
			TENNHOM=(SELECT NAME
			FROM sys.sysusers
				WHERE UID = (SELECT GROUPUID
					FROM SYS.SYSMEMBERS
						WHERE MEMBERUID= (SELECT UID FROM sys.sysusers
							WHERE NAME=@TENUSER)))
	END
END


