

CREATE PROC [dbo].[SP_CHECK_DANGNHAP]
@TENLOGIN NVARCHAR (50)
AS
BEGIN
	DECLARE @TENUSER NVARCHAR(50)
	SELECT @TENUSER=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)
	SELECT USERNAME = @TENUSER,
		HOTEN = (SELECT HO+ ' '+ TEN FROM GIANGVIEN WHERE MAGV = @TENUSER ),
		TENNHOM= NAME
			FROM sys.sysusers
				WHERE UID = (SELECT GROUPUID
					FROM SYS.SYSMEMBERS
						WHERE MEMBERUID= (SELECT UID FROM sys.sysusers
							WHERE NAME=@TENUSER))
END

CREATE PROC [dbo].[SP_CHECK_LOGIN_SV]
@TENLOGIN NVARCHAR (50), @MASV NCHAR(10), @PASS NVARCHAR(40)
AS
BEGIN
	IF EXISTS(SELECT * FROM SINHVIEN SV WHERE SV.MASV=@MASV AND SV.PASSWORD=@PASS)
	BEGIN
		DECLARE @TENUSER NVARCHAR(50)
		SELECT @TENUSER=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)

		SELECT MASV=@MASV, HOTEN=(SELECT HO+ ' '+ TEN FROM SINHVIEN WHERE MASV = @MASV ),
			TENNHOM=(SELECT NAME
			FROM sys.sysusers
				WHERE UID = (SELECT GROUPUID
					FROM SYS.SYSMEMBERS
						WHERE MEMBERUID= (SELECT UID FROM sys.sysusers
							WHERE NAME=@TENUSER)))
	END
END


CREATE PROCEDURE [dbo].[SP_GETMAKHOA]
AS
BEGIN 
    select MaKhoa from Khoa
END


CREATE proc [dbo].[SP_CHECKID]
@ID NCHAR(10),
@Type NCHAR(20)
AS
BEGIN 
    
	-- LOP
	IF(@Type = 'MALOP')
	BEGIN
		IF EXISTS(SELECT * FROM dbo.LOP WHERE dbo.LOP.MALOP = @ID)
				RETURN 1;--Mã LOP tồn tại ở phân hiện tại
		 IF EXISTS(SELECT * FROM LINK1.QLDSV_TC.dbo.LOP AS LOP WHERE LOP.MALOP = @ID)
			RETURN 2; --Mã Lớp tồn tại ở phân mãnh khác
	END

	 --MON HOC
	IF(@Type = 'MAMONHOC')
	BEGIN
		IF EXISTS(SELECT * FROM dbo.MONHOC AS MH WHERE MH.MAMH = @ID)
		RETURN 1;
	END

	 --SINH VIEN
	IF(@Type = 'MASV')
	BEGIN
	 IF EXISTS(SELECT * FROM dbo.SINHVIEN WHERE dbo.SINHVIEN.MASV = @ID)
			RETURN 1; -- Mã tồn tại ở phân mãnh hiện tại
	 IF EXISTS(SELECT * FROM LINK1.QLDSV_TC.dbo.SINHVIEN AS SV WHERE SV.MASV = @ID)
		RETURN 2; --Mã tồn tại ở phân mãnh khác
	END

	 RETURN 0 --Không bị trùng được thêm
END



CREATE proc [dbo].[SP_GET_LISTLOPTINCHI_DKI]
@Nienkhoa nchar(9),
@Hocky int,
@MaSV nchar(10)
as
BEGIN
	
select  MALTC,MAMH,TENMH=(select TENMH from MONHOC a where a.MAMH=ltc.MAMH),
		NHOM=ltc.NHOM, GIANGVIEN=(SELECT gv.HO+' '+gv.TEN FROM GIANGVIEN gv WHERE gv.MAGV=ltc.MAGV),
         DADANGKY=(select COUNT(*) from DANGKY dk where dk.MALTC = ltc.MALTC and (dk.HUYDANGKY =0 or dk.HUYDANGKY is null))
  from LOPTINCHI ltc
 WHERE ltc.NIENKHOA = @Nienkhoa and ltc.HOCKY = @Hocky and ltc.HUYLOP = 0 and 
 @MaSV not in (select MASV from DANGKY where MALTC =ltc.MALTC and (HUYDANGKY =0 or HUYDANGKY is null))
END

CREATE proc [dbo].[SP_GET_LISTLOPTINCHI_DADKI]
@Nienkhoa nchar(9),
@Hocky int,
@MaSV nchar(10)
as
BEGIN
	
select  MALTC,MAMH,TENMH=(select TENMH from MONHOC a where a.MAMH=ltc.MAMH),
		NHOM=ltc.NHOM, GIANGVIEN=(SELECT gv.HO+' '+gv.TEN FROM GIANGVIEN gv WHERE gv.MAGV=ltc.MAGV),
         DADANGKY=(select COUNT(*) from DANGKY dk where dk.MALTC = ltc.MALTC and (dk.HUYDANGKY =0 or dk.HUYDANGKY is null))
  from LOPTINCHI ltc
 WHERE ltc.NIENKHOA = @Nienkhoa and ltc.HOCKY = @Hocky and ltc.HUYLOP = 0 and 
 @MaSV in (select MASV from DANGKY where MALTC =ltc.MALTC and (HUYDANGKY =0 or HUYDANGKY is null))
END



create proc [dbo].[SP_DKY_LTC]
@MALTC int,
@MASV nchar(10)
AS
BEGIN 
  IF EXISTS ( SELECT * FROM DANGKY WHERE MALTC=@MALTC AND MASV=@MASV AND HUYDANGKY=1)
    BEGIN 
		UPDATE DANGKY 
		SET HUYDANGKY=0
		WHERE MALTC=@MALTC AND MASV=@MASV
	END
  ELSE
	BEGIN
		INSERT INTO DANGKY(MALTC,MASV) VALUES (@MALTC,@MASV)
	END

END


CREATE proc [dbo].[SP_HUY_DKY_LTC]
@MALTC int,
@MASV nchar(10)
AS
BEGIN 
  IF EXISTS ( SELECT * FROM DANGKY WHERE MALTC=@MALTC AND MASV=@MASV AND (HUYDANGKY=0 OR HUYDANGKY is null))
    BEGIN 
		UPDATE DANGKY 
		SET HUYDANGKY=1
		WHERE MALTC=@MALTC AND MASV=@MASV
	END
END

CREATE TYPE [dbo].[TYPE_DANGKY] AS TABLE(
	[MALTC] [int] NULL,
	[MASV] [nchar](10) NULL,
	[DIEM_CC] [int] NULL,
	[DIEM_GK] [float] NULL,
	[DIEM_CK] [float] NULL
)

CREATE PROCEDURE [dbo].[SP_SEARCH_LTC] @NienKhoa nchar(9), @HocKy int, @Nhom int,@MonHoc nchar(10)
as
BEGIN
declare @LOPTINCHI int
select @LOPTINCHI= MALTC
from LOPTINCHI JOIN MONHOC ON LOPTINCHI.MAMH = MONHOC.MAMH
where LOPTINCHI.NIENKHOA = @NienKhoa AND LOPTINCHI.HOCKY = @HocKy AND LOPTINCHI.NHOM = @Nhom
AND MONHOC.MAMH = @MonHoc 

select MALTC, MONHOC.TENMH, HOTEN=GIANGVIEN.HO+' '+GIANGVIEN.TEN
from  MONHOC JOIN (LOPTINCHI JOIN GIANGVIEN ON LOPTINCHI.MAGV = GIANGVIEN.MAGV) ON LOPTINCHI.MAMH = MONHOC.MAMH
where LOPTINCHI.MALTC =  @LOPTINCHI

END

CREATE proc [dbo].[SP_GETDIEMSV]
@MASV nchar(10)
AS
BEGIN
select NKHK=N'Học Kỳ '+ CAST(ltc.HOCKY as nvarchar(1))+N' - Năm học '+ltc.NIENKHOA,dk.MALTC,mh.TENMH,dk.DIEM_CC,dk.DIEM_GK,dk.DIEM_CK 
from DANGKY dk JOIN (select MALTC, NIENKHOA, HOCKY,MAMH FROM LOPTINCHI) ltc on dk.MALTC=ltc.MALTC 
				 JOIN (select MAMH,TenMH FROM MONHOC) mh ON ltc.MAMH = mh.MAMH
where dk.MASV=@MASV and( HUYDANGKY=0 or HUYDANGKY is NULL)
END

/* frm nhập điểm */
CREATE PROCEDURE [dbo].[SP_DSDKMH] @NienKhoa nchar(9), @HocKy int, @Nhom int,@MonHoc nchar(10)
as
BEGIN
	declare @LOPTINCHI int
	select @LOPTINCHI= MALTC 
	from LOPTINCHI JOIN MONHOC ON LOPTINCHI.MAMH = MONHOC.MAMH
	where LOPTINCHI.NIENKHOA = @NienKhoa AND LOPTINCHI.HOCKY = @HocKy AND LOPTINCHI.NHOM = @Nhom AND MONHOC.MAMH = @MonHoc 

	select @LOPTINCHI as LOPTC, SINHVIEN.MASV,HOTEN=HO+' '+TEN,DIEM_CC,DIEM_GK,DIEM_CK,DIEM_TK= DIEM_CC*0.1 + DIEM_GK*0.3 + DIEM_CK*0.6 
	from DANGKY JOIN SINHVIEN ON  DANGKY.MASV = SINHVIEN.MASV
	where DANGKY.MALTC = @LOPTINCHI AND HUYDANGKY = 0
END


create proc [dbo].[SP_UPDATEDIEM]
@DIEMTHI TYPE_DANGKY READONLY 
AS 
BEGIN 
	MERGE INTO DANGKY AS TARGET
	USING (SELECT MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK FROM @DIEMTHI) AS SOURCE
	ON TARGET.MALTC = SOURCE.MALTC AND TARGET.MASV = SOURCE.MASV 
	WHEN MATCHED THEN
		UPDATE SET TARGET.DIEM_CC = SOURCE.DIEM_CC,
				   TARGET.DIEM_GK = SOURCE.DIEM_GK,
				   TARGET.DIEM_CK = SOURCE.DIEM_CK
	WHEN NOT MATCHED THEN 
		INSERT ( MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK)
		 VALUES (SOURCE.MALTC, SOURCE.MASV, SOURCE.DIEM_CC, SOURCE.DIEM_GK, SOURCE.DIEM_CK);
END 


create proc [dbo].[SP_GET_NIENKHOA]
 as 
	select NIENKHOA from LOPTINCHI group by NIENKHOA


create proc [dbo].[SP_GET_HOCKY] 
@NIENKHOA nchar(9)  
as 
BEGIN 
	select HOCKY from LOPTINCHI 
	where NIENKHOA= @NIENKHOA group by HOCKY
END


create proc [dbo].[SP_GET_NHOM] 
@NIENKHOA varchar(9), @HOCKI int, @MAMH nchar(10)
as 
BEGIN
	select NHOM FROM LOPTINCHI 
	where @NIENKHOA = NIENKHOA AND HOCKY = @HOCKI AND MAMH = @MAMH 
	group by NHOM
END

create proc [dbo].[SP_GET_MONHOC] @NIENKHOA varchar(9), @HOCKI int
as
	 select MAMH FROM LOPTINCHI 
	 where @NIENKHOA = NIENKHOA AND HOCKY = @HOCKI  group by MAMH
GO


CREATE proc SP_CHANGEPASS @LOGIN nchar(10), @PASSOLD nvarchar(40), @PASSNEW nvarchar(40)
 AS
 BEGIN
	IF EXISTS ( SELECT 1 FROM SINHVIEN WHERE SINHVIEN.MASV = @LOGIN AND SINHVIEN.PASSWORD = @PASSOLD )
	   BEGIN
	      UPDATE SINHVIEN
		  SET SINHVIEN.PASSWORD = @PASSNEW
		  WHERE SINHVIEN.MASV = @LOGIN
		  RETURN;
	   END
	ELSE IF EXISTS ( SELECT 1 FROM SYS.sql_logins WHERE NAME = @LOGIN )
		BEGIN
			declare @SQLSTR nvarchar(200)
			Set @SQLSTR = 'ALTER LOGIN '+@LOGIN+' WITH PASSWORD= ' +QUOTENAME(@PASSNEW,'''')+ ' OLD_PASSWORD = '+QUOTENAME(@PASSOLD,'''')
			exec(@SQLSTR)
		END
	ELSE
	   Raiserror('Sai Mật Khẩu', 12, 1)

 END


 CREATE proc [dbo].[SP_REPORT_DS_LOPTINCHI]
@Nienkhoa nchar(9),
@Hocky int
as
BEGIN
	
select  TENMH=(select TENMH from MONHOC a where a.MAMH=ltc.MAMH),
		NHOM=ltc.NHOM, GIANGVIEN=(SELECT gv.HO+' '+gv.TEN FROM GIANGVIEN gv WHERE gv.MAGV=ltc.MAGV),
        ltc.SOSVTOITHIEU, DADANGKY=(select COUNT(*) from DANGKY dk where dk.MALTC = ltc.MALTC and (dk.HUYDANGKY =0 or dk.HUYDANGKY is null))
  from LOPTINCHI ltc
 WHERE ltc.NIENKHOA = @Nienkhoa and ltc.HOCKY = @Hocky and ltc.HUYLOP = 0 
END