

CREATE PROC [dbo].[SP_CHECK_DANGNHAP]
@TENLOGIN NVARCHAR (50)
AS
BEGIN
	DECLARE @TENUSER NVARCHAR(50)
	SELECT @TENUSER=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)
	SELECT USERNAME = @TENUSER,
		HOTEN = (SELECT HO+ ' '+ TEN FROM GIANGVIEN WHERE MAGV = @TENUSER ),
		TENNHOM= NAME
			FROM sys.sysusers
				WHERE UID = (SELECT GROUPUID
					FROM SYS.SYSMEMBERS
						WHERE MEMBERUID= (SELECT UID FROM sys.sysusers
							WHERE NAME=@TENUSER))
END

CREATE PROC [dbo].[SP_CHECK_LOGIN_SV]
@TENLOGIN NVARCHAR (50), @MASV NCHAR(10), @PASS NVARCHAR(40)
AS
BEGIN
	IF EXISTS(SELECT * FROM SINHVIEN SV WHERE SV.MASV=@MASV AND SV.PASSWORD=@PASS)
	BEGIN
		DECLARE @TENUSER NVARCHAR(50)
		SELECT @TENUSER=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)

		SELECT MASV=@MASV, HOTEN=(SELECT HO+ ' '+ TEN FROM SINHVIEN WHERE MASV = @MASV ),
			TENNHOM=(SELECT NAME
			FROM sys.sysusers
				WHERE UID = (SELECT GROUPUID
					FROM SYS.SYSMEMBERS
						WHERE MEMBERUID= (SELECT UID FROM sys.sysusers
							WHERE NAME=@TENUSER)))
	END
END


CREATE PROCEDURE [dbo].[SP_GETMAKHOA]
AS
BEGIN 
    select MaKhoa from Khoa
END


CREATE proc [dbo].[SP_CHECKID]
@ID NCHAR(10),
@Type NCHAR(20)
AS
BEGIN 
    
	-- LOP
	IF(@Type = 'MALOP')
	BEGIN
		IF EXISTS(SELECT * FROM dbo.LOP WHERE dbo.LOP.MALOP = @ID)
				RETURN 1;--Mã LOP tồn tại ở phân hiện tại
		 IF EXISTS(SELECT * FROM LINK1.QLDSV_TC.dbo.LOP AS LOP WHERE LOP.MALOP = @ID)
			RETURN 2; --Mã Lớp tồn tại ở phân mãnh khác
	END

	 --MON HOC
	IF(@Type = 'MAMONHOC')
	BEGIN
		IF EXISTS(SELECT * FROM dbo.MONHOC AS MH WHERE MH.MAMH = @ID)
		RETURN 1;
	END

	 --SINH VIEN
	IF(@Type = 'MASV')
	BEGIN
	 IF EXISTS(SELECT * FROM dbo.SINHVIEN WHERE dbo.SINHVIEN.MASV = @ID)
			RETURN 1; -- Mã tồn tại ở phân mãnh hiện tại
	 IF EXISTS(SELECT * FROM LINK1.QLDSV_TC.dbo.SINHVIEN AS SV WHERE SV.MASV = @ID)
		RETURN 2; --Mã tồn tại ở phân mãnh khác
	END

	 RETURN 0 --Không bị trùng được thêm
END

// frm nhập điểm 
ALTER PROCEDURE [dbo].[SP_DSDKMH] @NienKhoa nchar(9), @HocKy int, @Nhom int,@MonHoc nchar(10)
as
BEGIN
	declare @LOPTINCHI int
	select @LOPTINCHI= MALTC 
	from LOPTINCHI JOIN MONHOC ON LOPTINCHI.MAMH = MONHOC.MAMH
	where LOPTINCHI.NIENKHOA = @NienKhoa AND LOPTINCHI.HOCKY = @HocKy AND LOPTINCHI.NHOM = @Nhom AND MONHOC.MAMH = @MonHoc 

	select @LOPTINCHI as LOPTC, SINHVIEN.MASV,HOTEN=HO+' '+TEN,DIEM_CC,DIEM_GK,DIEM_CK,DIEM_TK= DIEM_CC*0.1 + DIEM_GK*0.3 + DIEM_CK*0.6 
	from DANGKY JOIN SINHVIEN ON  DANGKY.MASV = SINHVIEN.MASV
	where DANGKY.MALTC = @LOPTINCHI AND HUYDANGKY = 0
END


ALTER PROC [dbo].[SP_Ghi_DIEM]
@MSSV nchar(10),
@MALTC int,
@DIEM_CC float,
@DIEM_GK float,
@DIEM_CK float
as 
BEGIN
	IF EXISTS (Select 1 From DANGKY where MASV = @MSSV AND MALTC = @MALTC)
	BEGIN
		UPDATE DANGKY
		SET DIEM_CC = @DIEM_CC, DIEM_GK = @DIEM_GK, DIEM_CK = @DIEM_CK
		WHERE MASV = @MSSV AND MALTC = @MALTC
	END
	ELSE 
	RAISERROR(N'THÔNG TIN ĐĂNG KÝ KHÔNG TỒN TẠI',16,1)
END

ALTER proc [dbo].[sp_get_Nhom] @NIENKHOA varchar(9), @HOCKI int, @MAMH nchar(10)
as select NHOM FROM LOPTINCHI where @NIENKHOA = NIENKHOA AND HOCKY = @HOCKI AND MAMH = @MAMH group by NHOM

ALTER proc [dbo].[sp_get_MonHoc] @NIENKHOA varchar(9), @HOCKI int
as select MAMH FROM LOPTINCHI where @NIENKHOA = NIENKHOA AND HOCKY = @HOCKI  group by MAMH

ALTER proc [dbo].[sp_get_HocKy] @NIENKHOA nchar(9)  as 
select HOCKY from LOPTINCHI where NIENKHOA= @NIENKHOA group by HOCKY

ALTER proc [dbo].[sp_get_NienKhoa] as 
select NIENKHOA from LOPTINCHI group by NIENKHOA
